# Generated by Django 2.2.4 on 2023-06-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
