# Generated by Django 2.2.4 on 2023-07-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='localizacaoGPS',
        ),
        migrations.AddField(
            model_name='filial',
            name='idRestaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Restaurante'),
            preserve_default=False,
        ),
    ]
