# Generated by Django 2.2.4 on 2023-06-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0003_cadastrousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoFilialEventoExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssociacaoItemDeConsumoRecomendacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AssociacaoRestauranteUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoDoItem',
            fields=[
                ('idClassificacao', models.AutoField(primary_key=True, serialize=False)),
                ('descItem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoExterno',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('dataEvento', models.DateField()),
                ('horaEvento', models.TimeField()),
                ('rua', models.TextField()),
                ('numero', models.IntegerField()),
                ('bairro', models.TextField()),
                ('cidade', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('idFilial', models.AutoField(primary_key=True, serialize=False)),
                ('localizacaoGPS', models.TextField()),
                ('rua', models.TextField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('idGerente', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenteInterno',
            fields=[
                ('idIncidente', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.TextField()),
                ('idFilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial')),
                ('idGerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Gerente')),
            ],
        ),
        migrations.CreateModel(
            name='ItensDeConsumo',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False)),
                ('nomeItem', models.TextField()),
                ('precoItem', models.FloatField()),
                ('idClassificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.ClassificacaoDoItem')),
                ('idFilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial')),
            ],
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('idLotacao', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('dia', models.DateTimeField()),
                ('faixaHoraria', models.DateTimeField()),
                ('idFilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial')),
                ('idGerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Gerente')),
            ],
        ),
        migrations.CreateModel(
            name='NivelDeLotacao',
            fields=[
                ('idNivel', models.AutoField(primary_key=True, serialize=False)),
                ('descNivel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('idRecomendacao', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('idFilial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial')),
            ],
        ),
        migrations.CreateModel(
            name='Relacionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('idRestaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RevisaoDeComentario',
            fields=[
                ('idRevisao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('conteudo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeComida',
            fields=[
                ('idComida', models.AutoField(primary_key=True, serialize=False)),
                ('descComida', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeIncidenteInterno',
            fields=[
                ('idTipoIncidente', models.AutoField(primary_key=True, serialize=False)),
                ('descIncidente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeRelacionamento',
            fields=[
                ('idRelacionamento', models.AutoField(primary_key=True, serialize=False)),
                ('descTipoRelacionamento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('numeroTelefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.TextField()),
                ('cpf', models.IntegerField()),
                ('idRelacionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Relacionamento')),
            ],
        ),
        migrations.DeleteModel(
            name='cadastroUsuario',
        ),
        migrations.DeleteModel(
            name='postagem',
        ),
        migrations.DeleteModel(
            name='postagemcaduser',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='idComida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.TipoDeComida'),
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='idTipoRelacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.TipoDeRelacionamento'),
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='idUsuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idNivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.NivelDeLotacao'),
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
        ),
        migrations.AddField(
            model_name='incidenteinterno',
            name='idTipoIncidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.TipoDeIncidenteInterno'),
        ),
        migrations.AddField(
            model_name='incidenteinterno',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
        ),
        migrations.AddField(
            model_name='eventoexterno',
            name='idGerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Gerente'),
        ),
        migrations.AddField(
            model_name='eventoexterno',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
        ),
        migrations.AddField(
            model_name='associacaorestauranteusuario',
            name='idRestaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Restaurante'),
        ),
        migrations.AddField(
            model_name='associacaorestauranteusuario',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
        ),
        migrations.AddField(
            model_name='associacaoitemdeconsumorecomendacao',
            name='idItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.ItensDeConsumo'),
        ),
        migrations.AddField(
            model_name='associacaoitemdeconsumorecomendacao',
            name='idRecomendacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Recomendacao'),
        ),
        migrations.AddField(
            model_name='associacaofilialeventoexterno',
            name='idEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.EventoExterno'),
        ),
        migrations.AddField(
            model_name='associacaofilialeventoexterno',
            name='idFilial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial'),
        ),
    ]
