# Generated by Django 2.2.4 on 2023-07-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0003_gerente_idfilial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidenteinterno',
            old_name='idTipoIncidente',
            new_name='idTipoDeIncidente',
        ),
        migrations.RemoveField(
            model_name='incidenteinterno',
            name='local',
        ),
    ]
