# Generated by Django 2.2.4 on 2023-06-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0004_auto_20230622_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoexterno',
            name='idGerente',
        ),
        migrations.RemoveField(
            model_name='eventoexterno',
            name='idUsuario',
        ),
    ]
