# Generated by Django 2.2.4 on 2023-07-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0004_auto_20230717_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotacao',
            name='faixaHoraria',
        ),
    ]
