# Generated by Django 2.2.4 on 2023-07-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0005_remove_lotacao_faixahoraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='idItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.ItensDeConsumo'),
            preserve_default=False,
        ),
    ]
