# Generated by Django 2.2.4 on 2023-07-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0005_auto_20230623_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenteinterno',
            name='idFilial',
        ),
        migrations.RemoveField(
            model_name='incidenteinterno',
            name='idGerente',
        ),
        migrations.RemoveField(
            model_name='incidenteinterno',
            name='idTipoIncidente',
        ),
        migrations.RemoveField(
            model_name='incidenteinterno',
            name='idUsuario',
        ),
    ]
