# Generated by Django 2.2.4 on 2023-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0007_auto_20230717_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociacaoUsuarioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
