# Generated by Django 2.2.4 on 2023-07-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0007_auto_20230709_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensdeconsumo',
            name='idClassificacao',
        ),
        migrations.RemoveField(
            model_name='itensdeconsumo',
            name='idFilial',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='idFilial',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='idUsuario',
        ),
    ]
