# Generated by Django 2.2.4 on 2023-07-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0008_associacaousuariousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='associacaousuariousuario',
            name='idTipoRelacionamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.TipoDeRelacionamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='associacaousuariousuario',
            name='idUsuarioSecundario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
    ]
