# Generated by Django 2.2.4 on 2023-07-17 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0008_auto_20230709_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionamento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='relacionamento',
            name='idUsuario1',
        ),
        migrations.AddField(
            model_name='incidenteinterno',
            name='idFilial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenteinterno',
            name='idTipoIncidente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.TipoDeIncidenteInterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensdeconsumo',
            name='idClassificacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.ClassificacaoDoItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensdeconsumo',
            name='idFilial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idFilial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idNivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.NivelDeLotacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='idFilial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Filial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recomendacao',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relacionamento',
            name='idUsuario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
