# Generated by Django 2.2.4 on 2023-07-19 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0009_auto_20230717_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoexterno',
            name='idGerente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoexterno',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filial',
            name='nome',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenteinterno',
            name='idGerente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidenteinterno',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensdeconsumo',
            name='idGerente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensdeconsumo',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idGerente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotacao',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
    ]
