# Generated by Django 2.2.4 on 2023-07-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0011_remove_relacionamento_idusuario1'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacionamento',
            name='idUsuario1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='idRelacionamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.Relacionamento'),
            preserve_default=False,
        ),
    ]
