# Generated by Django 2.2.4 on 2023-07-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0012_auto_20230717_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relacionamento',
            name='idUsuario1',
        ),
    ]
