# Generated by Django 2.2.4 on 2023-07-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0014_remove_usuario_idrelacionamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionamento',
            old_name='idUsuario',
            new_name='idRelacionamento',
        ),
        migrations.RenameField(
            model_name='tipoderelacionamento',
            old_name='idRelacionamento',
            new_name='idTipoRelacionamento',
        ),
        migrations.AlterField(
            model_name='relacionamento',
            name='idTipoRelacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.TipoDeRelacionamento', to_field='idRelacionamento'),
        ),
    ]
