# Generated by Django 2.2.4 on 2023-07-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minhaAppProjetoFinal2', '0015_auto_20230717_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionamento',
            name='idTipoRelacionamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minhaAppProjetoFinal2.TipoDeRelacionamento'),
        ),
    ]
